name: drosak
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  # "To add assets to your application, add an assets section, like this": null
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: AA-GALAXY
      fonts:
        - asset: assets/fonts/aa_galaxy/AA-GALAXY.otf
    - family: ge_diner_one
      fonts:
        - asset: assets/fonts/ge_diner_one/ArbFONTS-GE-Dinar-One-Light.otf
        - asset: assets/fonts/ge_diner_one/ArbFONTS-GE-Dinar-One-Light.otf
          weight: 500
